"""Add summarized flag to mission_records

Revision ID: 0fbf5d6801d8
Revises: 92813afeaf50
Create Date: 2026-03-11 16:38:57.109341+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers
revision: str = '0fbf5d6801d8'
down_revision: Union[str, None] = '92813afeaf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_records', sa.Column('summarized', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True when compressed into a milestone summary by the summarization pipeline'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission_records', 'summarized')
    # ### end Alembic commands ###
