"""add project context layer tables

Revision ID: 1dc5c2cc9d93
Revises: 27c14af891b2
Create Date: 2026-03-11 08:35:58.482906+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# Revision identifiers
revision: str = '1dc5c2cc9d93'
down_revision: Union[str, None] = '27c14af891b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_changes',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('ADD', 'REPLACE', 'REMOVE', 'PRUNE', 'ARCHIVE', name='changetype', native_enum=False), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('old_value', sqlite.JSON(), nullable=True),
    sa.Column('new_value', sqlite.JSON(), nullable=True),
    sa.Column('agent_id', sa.String(length=200), nullable=True),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_changes_context_id'), 'context_changes', ['context_id'], unique=False)
    op.create_index(op.f('ix_context_changes_execution_id'), 'context_changes', ['execution_id'], unique=False)
    op.create_table('milestone_summaries',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('mission_ids', sqlite.JSON(), nullable=False),
    sa.Column('key_outcomes', sqlite.JSON(), nullable=False),
    sa.Column('domain_tags', sqlite.JSON(), nullable=False),
    sa.Column('period_start', sa.String(length=30), nullable=True),
    sa.Column('period_end', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_summaries_project_id'), 'milestone_summaries', ['project_id'], unique=False)
    op.create_table('project_contexts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('context_data', sqlite.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('size_characters', sa.Integer(), nullable=False),
    sa.Column('size_tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_contexts_project_id'), 'project_contexts', ['project_id'], unique=True)
    op.create_table('project_decisions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('made_by', sa.String(length=200), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'REVERSED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('superseded_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_decisions_domain'), 'project_decisions', ['domain'], unique=False)
    op.create_index(op.f('ix_project_decisions_project_id'), 'project_decisions', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MAINTAINER', 'VIEWER', name='projectmemberrole', native_enum=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.String(length=200), nullable=True),
    sa.Column('default_roster', sa.String(length=100), nullable=False),
    sa.Column('budget_ceiling_usd', sa.Float(), nullable=True),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('repo_root', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.add_column('mission_records', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_mission_records_project_id'), 'mission_records', ['project_id'], unique=False)
    op.add_column('missions', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_missions_project_id'), 'missions', ['project_id'], unique=False)
    op.add_column('playbook_runs', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_playbook_runs_project_id'), 'playbook_runs', ['project_id'], unique=False)
    op.add_column('task_executions', sa.Column('execution_id', sa.String(length=36), nullable=True, comment='Globally unique execution ID assigned at dispatch time'))
    op.add_column('task_executions', sa.Column('domain_tags', sqlite.JSON(), nullable=True, comment='Domain tags for structured history queries'))
    op.create_index(op.f('ix_task_executions_execution_id'), 'task_executions', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_execution_id'), table_name='task_executions')
    op.drop_column('task_executions', 'domain_tags')
    op.drop_column('task_executions', 'execution_id')
    op.drop_index(op.f('ix_playbook_runs_project_id'), table_name='playbook_runs')
    op.drop_column('playbook_runs', 'project_id')
    op.drop_index(op.f('ix_missions_project_id'), table_name='missions')
    op.drop_column('missions', 'project_id')
    op.drop_index(op.f('ix_mission_records_project_id'), table_name='mission_records')
    op.drop_column('mission_records', 'project_id')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_decisions_project_id'), table_name='project_decisions')
    op.drop_index(op.f('ix_project_decisions_domain'), table_name='project_decisions')
    op.drop_table('project_decisions')
    op.drop_index(op.f('ix_project_contexts_project_id'), table_name='project_contexts')
    op.drop_table('project_contexts')
    op.drop_index(op.f('ix_milestone_summaries_project_id'), table_name='milestone_summaries')
    op.drop_table('milestone_summaries')
    op.drop_index(op.f('ix_context_changes_execution_id'), table_name='context_changes')
    op.drop_index(op.f('ix_context_changes_context_id'), table_name='context_changes')
    op.drop_table('context_changes')
    # ### end Alembic commands ###
