"""add sessions notes missions playbook_runs tables

Revision ID: 27c14af891b2
Revises: 001_mission_records
Create Date: 2026-03-08 03:30:02.538918+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# Revision identifiers
revision: str = '27c14af891b2'
down_revision: Union[str, None] = '001_mission_records'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('playbook_run_id', sa.String(length=36), nullable=True),
    sa.Column('playbook_step_id', sa.String(length=100), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('roster_ref', sa.String(length=100), nullable=False),
    sa.Column('complexity_tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='missionstate', native_enum=False), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.String(length=200), nullable=False),
    sa.Column('upstream_context', sqlite.JSON(), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_ceiling_usd', sa.Float(), nullable=True),
    sa.Column('started_at', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('error_data', sqlite.JSON(), nullable=True),
    sa.Column('mission_outcome', sqlite.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_playbook_run_id'), 'missions', ['playbook_run_id'], unique=False)
    op.create_index(op.f('ix_missions_session_id'), 'missions', ['session_id'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('notes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    op.create_table('playbook_runs',
    sa.Column('playbook_name', sa.String(length=200), nullable=False),
    sa.Column('playbook_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='playbookrunstate', native_enum=False), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.String(length=200), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=True),
    sa.Column('started_at', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('error_data', sqlite.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_runs_playbook_name'), 'playbook_runs', ['playbook_name'], unique=False)
    op.create_index(op.f('ix_playbook_runs_session_id'), 'playbook_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_playbook_runs_status'), 'playbook_runs', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('goal', sa.String(length=2000), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_budget_usd', sa.Float(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_last_activity', 'sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('ix_sessions_user_status', 'sessions', ['user_id', 'status'], unique=False)
    op.create_table('session_channels',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=200), nullable=False),
    sa.Column('bound_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_channels_channel', 'session_channels', ['channel_type', 'channel_id'], unique=False)
    op.create_index('ix_session_channels_session', 'session_channels', ['session_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_session_channels_session_id'), 'session_channels', ['session_id'], unique=False)
    op.create_table('session_messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('tool_name', sa.String(length=200), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_messages_session_created', 'session_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)
    op.alter_column('mission_decisions', 'decision_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('RETRY', 'FAIL', 'PASS', 'RE_PLAN', 'SKIP', 'ESCALATE', name='decisiontype', native_enum=False),
               comment='retry, fail, pass, re_plan, skip, escalate',
               existing_nullable=False)
    op.alter_column('mission_decisions', 'task_id',
               existing_type=sa.VARCHAR(length=200),
               comment='Task ID from TaskPlan, if decision is task-specific',
               existing_nullable=True)
    op.alter_column('mission_decisions', 'reasoning',
               existing_type=sa.TEXT(),
               comment='Why Mission Control made this decision',
               existing_nullable=False)
    op.alter_column('mission_records', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Session that triggered this mission',
               existing_nullable=False)
    op.alter_column('mission_records', 'roster_name',
               existing_type=sa.VARCHAR(length=200),
               comment="Agent roster used (e.g. 'code_review', 'research')",
               existing_nullable=True)
    op.alter_column('mission_records', 'objective_statement',
               existing_type=sa.TEXT(),
               comment='Business outcome from Playbook Objective (null for ad-hoc missions)',
               existing_nullable=True)
    op.alter_column('mission_records', 'objective_category',
               existing_type=sa.VARCHAR(length=100),
               comment='Objective category from Playbook (enables filtering by business domain)',
               existing_nullable=True)
    op.alter_column('mission_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', name='missionrecordstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('mission_records', 'task_plan_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='TaskPlan dataclass serialized to JSON. Immutable after creation.',
               existing_nullable=True)
    op.alter_column('mission_records', 'mission_outcome_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='MissionOutcome dataclass serialized to JSON. Full execution result.',
               existing_nullable=True)
    op.alter_column('mission_records', 'planning_thinking_trace',
               existing_type=sa.TEXT(),
               comment='Planning Agent chain-of-thought for audit/debugging',
               existing_nullable=True)
    op.alter_column('mission_records', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='Total cost across all task executions',
               existing_nullable=False)
    op.alter_column('mission_records', 'parent_mission_id',
               existing_type=sa.VARCHAR(length=36),
               comment='If this mission was a re-plan, link to the original',
               existing_nullable=True)
    op.alter_column('task_attempts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PASSED', 'FAILED', name='taskattemptstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('task_attempts', 'failure_tier',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('TIER_1_STRUCTURAL', 'TIER_2_QUALITY', 'TIER_3_INTEGRATION', 'AGENT_ERROR', 'TIMEOUT', name='failuretier', native_enum=False),
               comment='Failure classification from verification',
               existing_nullable=True)
    op.alter_column('task_attempts', 'failure_reason',
               existing_type=sa.TEXT(),
               comment='Why this attempt failed',
               existing_nullable=True)
    op.alter_column('task_attempts', 'feedback_provided',
               existing_type=sa.TEXT(),
               comment='Feedback injected into agent prompt for next attempt',
               existing_nullable=True)
    op.alter_column('task_attempts', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_attempts', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_attempts', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_executions', 'task_id',
               existing_type=sa.VARCHAR(length=200),
               comment='Task ID from the TaskPlan JSON',
               existing_nullable=False)
    op.alter_column('task_executions', 'agent_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Agent that executed this task',
               existing_nullable=False)
    op.alter_column('task_executions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('COMPLETED', 'FAILED', 'SKIPPED', name='taskexecutionstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('task_executions', 'output_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Structured output from the agent',
               existing_nullable=True)
    op.alter_column('task_executions', 'token_usage',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='{"input_tokens": int, "output_tokens": int, "model": str}',
               existing_nullable=True)
    op.alter_column('task_executions', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_executions', 'verification_outcome',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Tier 1/2/3 verification result from Plan 14',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_executions', 'verification_outcome',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Tier 1/2/3 verification result from Plan 14',
               existing_nullable=True)
    op.alter_column('task_executions', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('task_executions', 'token_usage',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"input_tokens": int, "output_tokens": int, "model": str}',
               existing_nullable=True)
    op.alter_column('task_executions', 'output_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured output from the agent',
               existing_nullable=True)
    op.alter_column('task_executions', 'status',
               existing_type=sa.Enum('COMPLETED', 'FAILED', 'SKIPPED', name='taskexecutionstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('task_executions', 'agent_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Agent that executed this task',
               existing_nullable=False)
    op.alter_column('task_executions', 'task_id',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Task ID from the TaskPlan JSON',
               existing_nullable=False)
    op.alter_column('task_attempts', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('task_attempts', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('task_attempts', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('task_attempts', 'feedback_provided',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Feedback injected into agent prompt for next attempt',
               existing_nullable=True)
    op.alter_column('task_attempts', 'failure_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Why this attempt failed',
               existing_nullable=True)
    op.alter_column('task_attempts', 'failure_tier',
               existing_type=sa.Enum('TIER_1_STRUCTURAL', 'TIER_2_QUALITY', 'TIER_3_INTEGRATION', 'AGENT_ERROR', 'TIMEOUT', name='failuretier', native_enum=False),
               type_=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Failure classification from verification',
               existing_nullable=True)
    op.alter_column('task_attempts', 'status',
               existing_type=sa.Enum('PASSED', 'FAILED', name='taskattemptstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('mission_records', 'parent_mission_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='If this mission was a re-plan, link to the original',
               existing_nullable=True)
    op.alter_column('mission_records', 'total_cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               comment=None,
               existing_comment='Total cost across all task executions',
               existing_nullable=False)
    op.alter_column('mission_records', 'planning_thinking_trace',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Planning Agent chain-of-thought for audit/debugging',
               existing_nullable=True)
    op.alter_column('mission_records', 'mission_outcome_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='MissionOutcome dataclass serialized to JSON. Full execution result.',
               existing_nullable=True)
    op.alter_column('mission_records', 'task_plan_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='TaskPlan dataclass serialized to JSON. Immutable after creation.',
               existing_nullable=True)
    op.alter_column('mission_records', 'status',
               existing_type=sa.Enum('COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', name='missionrecordstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('mission_records', 'objective_category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Objective category from Playbook (enables filtering by business domain)',
               existing_nullable=True)
    op.alter_column('mission_records', 'objective_statement',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Business outcome from Playbook Objective (null for ad-hoc missions)',
               existing_nullable=True)
    op.alter_column('mission_records', 'roster_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Agent roster used (e.g. 'code_review', 'research')",
               existing_nullable=True)
    op.alter_column('mission_records', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Session that triggered this mission',
               existing_nullable=False)
    op.alter_column('mission_decisions', 'reasoning',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Why Mission Control made this decision',
               existing_nullable=False)
    op.alter_column('mission_decisions', 'task_id',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Task ID from TaskPlan, if decision is task-specific',
               existing_nullable=True)
    op.alter_column('mission_decisions', 'decision_type',
               existing_type=sa.Enum('RETRY', 'FAIL', 'PASS', 'RE_PLAN', 'SKIP', 'ESCALATE', name='decisiontype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='retry, fail, pass, re_plan, skip, escalate',
               existing_nullable=False)
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_index('ix_session_messages_session_created', table_name='session_messages')
    op.drop_table('session_messages')
    op.drop_index(op.f('ix_session_channels_session_id'), table_name='session_channels')
    op.drop_index('ix_session_channels_session', table_name='session_channels')
    op.drop_index('ix_session_channels_channel', table_name='session_channels')
    op.drop_table('session_channels')
    op.drop_index('ix_sessions_user_status', table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_last_activity', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_playbook_runs_status'), table_name='playbook_runs')
    op.drop_index(op.f('ix_playbook_runs_session_id'), table_name='playbook_runs')
    op.drop_index(op.f('ix_playbook_runs_playbook_name'), table_name='playbook_runs')
    op.drop_table('playbook_runs')
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_session_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_playbook_run_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
